apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: e1f4tsbln-go 
  janus-idp.io/tekton: e1f4tsbln-go
  backstage.io/kubernetes-id: e1f4tsbln-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e1f4tsbln-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  